calorie_map = {
    "Biriyani": 198,               
    "Boiled_egg": 155,             
    "Buter_Dal": 145,              
    "Cake": 310,                   
    "cheesecake": 360,             
    "Chicken_curry": 250,          
    "Chicken_wings": 305,          
    "Chocolate_cake": 335,         
    "Chow_mein": 210,              
    "Crab_Dish_Kakra": 261,        
    "cup_cakes": 330,              
    "Fish Bhuna_Mach Bhuna": 323,  
    "French_fries": 294,           
    "Fried fish_Mach Bhaja": 280,  
    "Fried_rice": 250,             
    "Hilsha_Fish_Curry": 270,      
    "ice_cream": 267,              
    "Kacchi": 225,                 
    "kebab_Gosht Kebab": 320,      
    "Khichuri": 176,               
    "Lentil fritters_Dal Puri": 190, 
    "Lentil soup_Dal": 110,        
    "Meat Curry_Gosht Bhuna": 280, 
    "Misti": 250,                  
    "omelette": 220,               
    "pizza": 285,                  
    "poached_egg": 160,            
    "Salad": 40,                   
    "Sandwich": 275,               
    "Shik_kabab": 320,             
    "Singgara": 285,               
    "steak": 271,                  
    "Vegetable fritters _Beguni": 180, 
    "Vorta": 150                   
}
